# ============================================================
# KLICKYDOCK MENU
# Include this file in the KlipperScreen.conf
# ============================================================

[menu __main more klickdock]
name: KlickyDock
icon: settings
panel: KlickyDock


# ------------------------------------------------------------
# DEPLOY
# ------------------------------------------------------------

[menu __main more klickdock deploy]
name: Deploy
icon: arrow-down
method: printer.gcode.script
params: {"script":"KLICKYDOCK_DEPLOY"}


# ------------------------------------------------------------
# RETRACT
# ------------------------------------------------------------

[menu __main more klickdock retract]
name: Retract
icon: arrow-up
method: printer.gcode.script
params: {"script":"KLICKYDOCK_RETRACT"}


# ------------------------------------------------------------
# DEPLOY MOVE
# ------------------------------------------------------------
#
# KlipperScreen's normal custom menu does not support a
# numeric input box here.
#
# This can be replaced with a custom KlickDock panel that
# provides +/- controls and/or a numeric input.
#
# ------------------------------------------------------------


# ------------------------------------------------------------
# RETRACT MOVE
# ------------------------------------------------------------
#
# KlipperScreen's normal custom menu does not support a
# numeric input box here.
#
# This can be replaced with a custom KlickDock panel that
# provides +/- controls and/or a numeric input.
#
# ------------------------------------------------------------


# ------------------------------------------------------------
# SAVE
# ------------------------------------------------------------

[menu __main more klickdock save]
name: Save
icon: complete
method: printer.gcode.script
params: {"script":"KLICKYDOCK_SAVE"}


# ------------------------------------------------------------
# ENABLE SERVO
# ------------------------------------------------------------

[menu __main more klickdock enable]
name: Enable
icon: power
method: printer.gcode.script
params: {"script":"KLICKYDOCK_ENABLE"}


# ------------------------------------------------------------
# DISABLE SERVO
# ------------------------------------------------------------

[menu __main more klickdock disable]
name: Disable
icon: shutdown
method: printer.gcode.script
params: {"script":"KLICKYDOCK_DISABLE"}
